name: Tak Server CI/CD Prod

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        mvn -B compile
        mvn -B package
    - name: Prep Artifact
      env:
        PROPERTIES : ${{ secrets.PROPERTIES }}
      run : |
        rm properties.xml
        touch properties.xml
        echo "${PROPERTIES}" >> properties.xml
        mkdir dist
        mv properties.xml ./dist
        mv ./target/takserver-jar-with-dependencies.jar ./dist/takserver-prod.jar
        tar -czf artifact-prod.tar.gz ./dist/*
    - name: Deploy
      env: 
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY  }}
          HOSTNAME : ${{ secrets.HOSTNAME }}
          USER_NAME : ${{ secrets.USER_NAME }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem && chmod 0400 private_key.pem
        scp -P ${SSH_PORT} -o StrictHostKeyChecking=no -i private_key.pem artifact-prod.tar.gz ${USER_NAME}@${HOSTNAME}:~
        ssh -p ${SSH_PORT} -o StrictHostKeyChecking=no -i private_key.pem ${USER_NAME}@${HOSTNAME} '
          source /etc/profile
          echo "setting up tmp folder"
          rm -rf playtak-server-prod-tmp
          mkdir playtak-server-prod-tmp
          echo "extracting artifact"
          tar -xzf artifact-prod.tar.gz -C ./playtak-server-prod-tmp
          echo "stopping existing prod takserver"
          sudo systemctl stop takserver-prod.service
          echo "rsyncing files into prod folder"
          sudo rsync -a playtak-server-prod-tmp/dist/ /var/apps/playtak-server-prod
          echo "Starting app"
          sudo systemctl start takserver-prod.service
        '